package com.applicationtracker.backend;

import com.applicationtracker.backend.models.JobApplication;
import com.applicationtracker.backend.services.JobApplicationService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.time.LocalDateTime;

@SpringBootTest
class JobApplicationTests {

    @Autowired
    private JobApplicationService jobApplicationService;

    private JobApplication testApplication;

    @BeforeEach
    void setUp() {
        // Prepare a sample job application object before each test
        testApplication = new JobApplication();
        testApplication.setCompanyName("Google");
        testApplication.setJobTitle("Software Engineer Intern");
        testApplication.setPortalLink("https://careers.google.com");
        testApplication.setContactName("Recruiter Team");
        testApplication.setContactEmail("recruiter@google.com");
        testApplication.setApplicationDate(LocalDateTime.now());
        testApplication.setStatus("In Progress");
        testApplication.setNotes("First round technical interview scheduled");
        testApplication.setUserId(1L);
    }

    @AfterEach
    void tearDown() {
        // Clean up the created test application from DB after test execution
        if (testApplication != null && testApplication.getApplicationId() != null) {
            try {
                jobApplicationService.delete(testApplication.getApplicationId());
                System.out.println("🧹 Cleaned up test application ID: " + testApplication.getApplicationId());
            } catch (Exception e) {
                // Ignore if already deleted
            }
        }
    }

    @Test
    @DisplayName("Test 1: User creates a new Job Application successfully")
    void testCreateJobApplicationSuccess() {
        System.out.println("==================================================");
        System.out.println("🚀 RUNNING JUNIT TEST: CREATE JOB APPLICATION");
        System.out.println("==================================================");

        // 1. Execute the create application service method
        JobApplication savedApplication = jobApplicationService.create(testApplication);

        // 2. Assertions to verify the entity was saved correctly
        Assertions.assertNotNull(savedApplication, "Saved application should not be null");
        Assertions.assertNotNull(savedApplication.getApplicationId(), "Application ID should be auto-generated by the database");
        Assertions.assertEquals("Google", savedApplication.getCompanyName(), "Company name should match input");
        Assertions.assertEquals("Software Engineer Intern", savedApplication.getJobTitle(), "Job title should match input");
        Assertions.assertEquals("In Progress", savedApplication.getStatus(), "Status should match input");
        Assertions.assertEquals(1L, savedApplication.getUserId(), "User ID should match input");

        System.out.println("✅ TEST PASSED: Job Application created successfully!");
        System.out.println("   Assigned Application ID: " + savedApplication.getApplicationId());
        System.out.println("   Company Name: " + savedApplication.getCompanyName());
        System.out.println("   Job Title: " + savedApplication.getJobTitle());
        System.out.println("   Status: " + savedApplication.getStatus());
        System.out.println("==================================================");
    }

    @Test
    @DisplayName("Test 2: Retrieve created Job Application by ID")
    void testGetJobApplicationById() {
        System.out.println("==================================================");
        System.out.println("🚀 RUNNING JUNIT TEST: RETRIEVE APPLICATION BY ID");
        System.out.println("==================================================");

        // 1. Save application first
        JobApplication savedApplication = jobApplicationService.create(testApplication);

        // 2. Retrieve the application using getById
        JobApplication foundApplication = jobApplicationService.getById(savedApplication.getApplicationId());

        // 3. Assertions
        Assertions.assertNotNull(foundApplication, "Fetched application should not be null");
        Assertions.assertEquals(savedApplication.getApplicationId(), foundApplication.getApplicationId());
        Assertions.assertEquals("Google", foundApplication.getCompanyName());

        System.out.println("✅ TEST PASSED: Successfully retrieved Job Application by ID!");
        System.out.println("==================================================");
    }
}
